baseURL = "/"
languageCode = "en-us"
title = "My Blog"
theme = "beautifulhugo"

[Params]
  subtitle = "Test"
  rss = true
  readingTime = true
  useHLJS = true
  dateFormat = "Monday, January 2, 2006"
  #logo = "img/avatar-icon.png"
  #favicon = "img/favicon.ico"

[Author]
  name = "Madison Solarana"
  github = "madsolar8582"
  twitter = "madisonsolarana"
  linkedin = "madison-solarana"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 3
