baseURL = "https://msolarana.netlify.app/"
languageCode = "en-us"
theme = "paper"
title = "Madison's Blog"
pygmentsUseClasses = true

[Author]
  name = "Madison Solarana"

[Params]
  description = "A collection of ramblings, thoughts, and ideas"

[Taxonomies]
  tag = "tags"

[Permalinks]
  post = "/:year/:month/:day/:title/"

[menu]
  [[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 1

  [[menu.main]]
    name = "Archives"
    url = "/page/archives/"
    weight = 2

  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 3

[markup]
  [markup.highlight]
    style = "base16-snazzy"
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
