baseURL = "https://msolarana.netlify.com/"
title = "Home"
languageCode = "en-us"
theme = "ghostwriter"
copyright = "Madison Solarana"

[Privacy]

[Privacy.disqus]
  disable = true

[Privacy.googleAnalytics]
  anonymizeIP = true
  respectDoNotTrack = true
  useSessionStorage = false

[Params]
  intro = true
  headline = "Madison's Blog"
  description = "A collection of ramblings, thoughts, and ideas"
  dateFormat = "Monday, January 2, 2006"
  github = "https://github.com/madsolar8582"
  linkedin = "https://linkedin.com/in/madisonsolarana"
  twitter = "https://twitter.com/madisonsolarana"
  opengraph = false
  shareTwitter = true
  shareFacebook = true
  shareGooglePlus = true
  shareLinkedIn = true

[Author]
  name = "Madison Solarana"

[Taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3
