[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.79.1"
HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Download-Options = "noopen"
    Expect-CT = "max-age=31536000, enforce"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'none'; font-src 'self'; frame-src 'self'; img-src 'self'; script-src 'self' static.cloudflareinsights.com; style-src 'self'; upgrade-insecure-requests; block-all-mixed-content; object-src 'none'; frame-ancestors 'none'; form-action 'self'; manifest-src 'self'; connect-src 'self' https://cloudflareinsights.com; base-uri 'self'; media-src 'self'; require-trusted-types-for 'script';"

[[redirects]]
  from = "http://msolarana.netlify.app/*"
  to = "https://msolarana.netlify.app/:splat"
  status = 301
  force = true
