[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.46"
HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Download-Options = "noopen"
    Expect-CT = "max-age=31536000, enforce"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'none'; font-src https: data: https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com; frame-src https: https://platform.twitter.com https://www.youtube.com; img-src 'self' https: data: https://platform.twitter.com; script-src 'self' 'unsafe-inline' https://cdn.syndication.twimg.com/tweets.json https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js https://platform.twitter.com/js/tweet.94890a17f454cac616ec67c343f98d96.js https://platform.twitter.com/widgets.js; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/ https://platform.twitter.com/css/tweet.491ab81a49d69599f35b92d184213601.light.ltr.css https://platform.twitter.com/css/tweet.491ab81a49d69599f35b92d184213601.light.rtl.css; upgrade-insecure-requests; block-all-mixed-content; object-src 'none'; worker-src 'self'; frame-ancestors 'none'; form-action 'self'; manifest-src 'self'; connect-src 'self'; base-uri 'self';"

[[redirects]]
  from = "http://msolarana.netlify.com/*"
  to = "https://msolarana.netlify.com/:splat"
  status = 301
  force = true
