[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.44"
HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [[headers.values]]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Download-Options = "noopen"
    Expect-CT = "max-age=31536000, enforce"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
